
version: '3.7'

networks:
  web:
    name: web

services:
  web:
    image: indava/php:7.4
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=phpmx"
      - "traefik.http.routers.web.rule=Host(`bot.phpmexico.mx`)"
    environment:
      - APP_ENV=prod
      - WEB_ROOT=public
      - PHP_TIMEZONE=America/Mexico_City
      - PHP_MEMORY=64M
      - APACHE_RUN_USER=web
    volumes:
      - ./:/var/www/html